import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#f5f3ef',
  },
  header: {
    backgroundColor: '#1A0533',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: -0.3,
  },
  headerSub: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.45)',
    marginTop: 2,
    fontWeight: '500',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#4ade80',
  },
  liveText: {
    fontSize: 11,
    color: '#4ade80',
    fontWeight: '700',
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 4,
  },
  avatarText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#fff',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
  },
  alertRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  alertBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  alertBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
  },
  statCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    width: (width - 42) / 2,
    borderWidth: 1,
    borderColor: '#ece9e4',
    overflow: 'hidden',
  },
  statAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  statValue: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: -0.5,
    marginTop: 8,
  },
  statLabel: {
    fontSize: 11,
    color: '#888',
    marginTop: 4,
    fontWeight: '500',
  },
  statDelta: {
    fontSize: 10,
    color: '#5C1A1A',
    marginTop: 4,
    fontWeight: '700',
  },
  section: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#ece9e4',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: -0.2,
    marginBottom: 14,
  },
  pendingPill: {
    backgroundColor: '#fef3c7',
    borderRadius: 50,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginBottom: 14,
  },
  pendingPillText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#92400e',
  },
  verifyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#f5f3f0',
    gap: 10,
  },
  verifyAvatar: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#f0ece8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  verifyAvatarText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#5C1A1A',
  },
  verifyInfo: {
    flex: 1,
  },
  verifyName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  verifySub: {
    fontSize: 11,
    color: '#999',
    marginTop: 2,
  },
  verifyBtns: {
    flexDirection: 'row',
    gap: 6,
  },
  approveBtn: {
    backgroundColor: '#1A0533',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  approveBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#fff',
  },
  rejectBtn: {
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  rejectBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#666',
  },
  flagCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f9f8f6',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    gap: 10,
  },
  flagDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  flagInfo: {
    flex: 1,
  },
  flagTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  flagDetail: {
    fontSize: 11,
    color: '#999',
    marginTop: 2,
  },
  reviewBtn: {
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#e0dcd6',
  },
  reviewBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#333',
  },
  mgmtGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  mgmtCard: {
    backgroundColor: '#f9f8f6',
    borderRadius: 14,
    padding: 14,
    width: (width - 68) / 2,
    borderWidth: 1,
    borderColor: '#ece9e4',
  },
  mgmtIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  mgmtLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  mgmtSub: {
    fontSize: 11,
    color: '#999',
    marginTop: 2,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#f5f3f0',
  },
  activityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  activityInfo: {
    flex: 1,
  },
  activityTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1a1a1a',
  },
  activitySub: {
    fontSize: 11,
    color: '#999',
    marginTop: 2,
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#ece9e4',
    flexDirection: 'row',
    height: 68,
    paddingBottom: 8,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  navIcon: {
    fontSize: 20,
  },
  navLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: '#bbb',
    letterSpacing: 0.2,
  },
  navLabelActive: {
    color: '#1A0533',
  },
  navActiveDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#1A0533',
    marginTop: 1,
  },
});