import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#f5f3ef',
  },
  header: {
    backgroundColor: '#5C1A1A',
    paddingHorizontal: 20,
    paddingTop: 48, // Notch offset
    paddingBottom: 18,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoBadge: {
    backgroundColor: '#fff',
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoBadgeText: {
    color: '#5C1A1A',
    fontSize: 14,
    fontWeight: '800',
  },
  brand: {
    flexDirection: 'column',
  },
  brandName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: -0.3,
  },
  brandSub: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.45)',
    marginTop: 1,
    fontWeight: '500',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  notifBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  notifBtnText: {
    fontSize: 11,
    color: '#fff',
    fontWeight: '600',
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.18)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#fff',
  },
  greeting: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 14,
    paddingBottom: 120, // Tall space for safe footer
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#888',
    textTransform: 'uppercase',
    marginTop: 18,
    marginBottom: 10,
  },
  buildCaseBtn: {
    backgroundColor: '#5C1A1A',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  buildCaseBtnText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  lawyerRow: {
    flexDirection: 'row',
    gap: 14,
    paddingVertical: 4,
  },
  lawyerBubble: {
    alignItems: 'center',
    width: 90,
    backgroundColor: '#fff',
    padding: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ece9e4',
  },
  lawyerAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lawyerAvatarText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#fff',
  },
  lawyerName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#333',
    textAlign: 'center',
    marginTop: 6,
  },
  lawyerSpec: {
    fontSize: 9,
    color: '#999',
    textAlign: 'center',
  },
  ratingContainer: {
    marginTop: 4,
  },
  ratingText: {
    fontSize: 9,
    color: '#666',
    fontWeight: '700',
  },
  sbcBadge: {
    fontSize: 8,
    color: '#5C1A1A',
    fontWeight: '700',
    backgroundColor: '#f5e8e8',
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginTop: 4,
  },
  emptyText: {
    color: '#666',
    fontStyle: 'italic',
    padding: 10,
  },
  caseItem: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#ece9e4',
  },
  caseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  caseInfo: {
    flex: 1,
  },
  caseTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1a1a1a',
  },
  caseSub: {
    fontSize: 11,
    color: '#999',
    marginTop: 2,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#5C1A1A',
    backgroundColor: '#f5e8e8',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#ece9e4',
    flexDirection: 'row',
    height: 80, // Taller footer
    paddingBottom: 24, // Shift icons higher away from gesture bars
    paddingTop: 10,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#bbb',
  },
  navLabelActive: {
    color: '#5C1A1A',
  },
  navActiveDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#5C1A1A',
    marginTop: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  popupContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 360,
  },
  popupTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 8,
    textAlign: 'center',
  },
  popupSubtitle: {
    fontSize: 13,
    color: '#666',
    marginBottom: 20,
    textAlign: 'center',
    lineHeight: 18,
  },
  caseTypeOption: {
    padding: 14,
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e8e8e8',
  },
  caseTypeInfo: {
    flex: 1,
  },
  caseTypeTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 4,
  },
  caseTypeDesc: {
    fontSize: 12,
    color: '#666',
    lineHeight: 16,
  },
  popupCloseBtn: {
    marginTop: 8,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 12,
  },
  popupCloseBtnText: {
    fontSize: 15,
    color: '#666',
    fontWeight: '600',
  },
  lawyerProfileContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 380,
    maxHeight: '80%',
  },
  closeProfileBtn: {
    alignSelf: 'flex-end',
    marginBottom: 10,
  },
  closeProfileText: {
    fontSize: 14,
    color: '#5C1A1A',
    fontWeight: '700',
  },
  profileAvatarLarge: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 10,
  },
  profileAvatarText: {
    fontSize: 24,
    fontWeight: '800',
    color: '#fff',
  },
  profileName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a1a',
    textAlign: 'center',
  },
  profileSpec: {
    fontSize: 13,
    color: '#888',
    textAlign: 'center',
    marginBottom: 14,
  },
  profileDetails: {
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 10,
    marginBottom: 14,
  },
  profileDetailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  profileDetailLabel: {
    fontSize: 11,
    color: '#888',
  },
  profileDetailValue: {
    fontSize: 11,
    color: '#1a1a1a',
    fontWeight: '600',
  },
  profileAbout: {
    fontSize: 12,
    color: '#555',
    lineHeight: 18,
    marginBottom: 14,
    textAlign: 'center',
  },
  scheduleBtn: {
    backgroundColor: '#f5e8e8',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 14,
  },
  scheduleBtnText: {
    color: '#5C1A1A',
    fontSize: 12,
    fontWeight: '700',
  },
  reviewsTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 8,
  },
  reviewCard: {
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#eee',
  },
  reviewUser: {
    fontSize: 11,
    fontWeight: '700',
    color: '#333',
  },
  reviewComment: {
    fontSize: 11,
    color: '#666',
    marginTop: 2,
  },
  sendRequestBtn: {
    backgroundColor: '#5C1A1A',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },
  sendRequestBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  requestSentContainer: {
    backgroundColor: '#dcfce7',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },
  requestSentText: {
    color: '#166534',
    fontSize: 14,
    fontWeight: '700',
  },
  scheduleItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  scheduleDay: {
    fontSize: 13,
    fontWeight: '700',
    color: '#333',
  },
  scheduleTime: {
    fontSize: 13,
    color: '#666',
  },
});