import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#f5f3ef',
  },
  header: {
    backgroundColor: '#5C1A1A',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 52 : 44,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#ece9e4',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoBadge: {
    backgroundColor: '#ffffff',
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#5C1A1A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  logoBadgeText: {
    color: '#5C1A1A',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  brand: {
    flexDirection: 'column',
  },
  brandName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: -0.4,
  },
  brandSub: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 1,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  profileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  profileBtnText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '700',
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#5C1A1A',
  },
  greeting: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 120,
  },

  // HERO BANNER
  bannerCard: {
    backgroundColor: '#5C1A1A',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#5C1A1A',
    shadowColor: '#5C1A1A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    position: 'relative',
    overflow: 'hidden',
  },
  bannerTag: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.2,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  bannerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: -0.3,
    marginBottom: 6,
  },
  bannerSub: {
    fontSize: 13,
    color: '#f5e8e8',
    lineHeight: 19,
    marginBottom: 16,
  },
  bannerBtn: {
    backgroundColor: '#ffffff',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
    alignSelf: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  bannerBtnText: {
    color: '#5C1A1A',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.2,
  },

  // SECTION HEADERS
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 12,
  },
  sectionLabel: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: -0.2,
  },
  seeAllText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#5C1A1A',
  },

  // SEARCH BAR
  searchBarWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#ece9e4',
    marginBottom: 14,
  },
  searchIcon: {
    fontSize: 16,
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    color: '#1a1a1a',
    fontSize: 14,
    fontWeight: '500',
  },
  filterScroll: {
    marginBottom: 16,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ece9e4',
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: '#5C1A1A',
    borderColor: '#5C1A1A',
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666666',
  },
  filterChipTextActive: {
    color: '#ffffff',
    fontWeight: '800',
  },

  // CASE CARDS
  caseCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#ece9e4',
  },
  caseCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  caseCategory: {
    fontSize: 11,
    fontWeight: '800',
    color: '#5C1A1A',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  statusPill: {
    backgroundColor: '#f5e8e8',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(92, 26, 26, 0.2)',
  },
  statusText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#5C1A1A',
  },
  caseTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 6,
  },
  caseLawyer: {
    fontSize: 13,
    color: '#666666',
    marginBottom: 4,
  },
  caseDate: {
    fontSize: 12,
    color: '#5C1A1A',
    fontWeight: '600',
  },

  // REQUEST STATUS CARDS (OPTIMISTIC TRACKER)
  reqCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#ece9e4',
  },
  reqCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  reqLawyerName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  reqStatusPillPending: {
    backgroundColor: '#fef3c7',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  reqStatusPillAccepted: {
    backgroundColor: '#dcfce7',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  reqStatusPillDeclined: {
    backgroundColor: '#fee2e2',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#fca5a5',
  },
  reqStatusTextPending: {
    fontSize: 11,
    fontWeight: '800',
    color: '#b45309',
  },
  reqStatusTextAccepted: {
    fontSize: 11,
    fontWeight: '800',
    color: '#15803d',
  },
  reqStatusTextDeclined: {
    fontSize: 11,
    fontWeight: '800',
    color: '#b91c1c',
  },
  reqReason: {
    fontSize: 13,
    color: '#444444',
    lineHeight: 18,
    marginBottom: 8,
  },
  reqMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reqMetaText: {
    fontSize: 11,
    color: '#888888',
    fontWeight: '500',
  },

  // LAWYER CARDS (HORIZ / GRID)
  lawyerScroll: {
    marginBottom: 10,
  },
  lawyerCard: {
    width: 175,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 14,
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#ece9e4',
    alignItems: 'center',
  },
  lawyerAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    position: 'relative',
  },
  onlineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#10b981',
    position: 'absolute',
    bottom: 0,
    right: 0,
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  lawyerAvatarText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#ffffff',
  },
  lawyerName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1a1a1a',
    textAlign: 'center',
    marginBottom: 2,
  },
  lawyerSpec: {
    fontSize: 11,
    color: '#5C1A1A',
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 4,
  },
  lawyerSbc: {
    fontSize: 10,
    color: '#888888',
    fontWeight: '600',
    marginBottom: 8,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 12,
  },
  ratingText: {
    fontSize: 12,
    color: '#1a1a1a',
    fontWeight: '700',
  },
  hireBtn: {
    width: '100%',
    backgroundColor: '#5C1A1A',
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
  },
  hireBtnText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },

  // BOTTOM NAV
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    height: 80,
    paddingBottom: 24,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#ece9e4',
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#bbbbbb',
  },
  navLabelActive: {
    color: '#5C1A1A',
    fontWeight: '800',
  },
});