import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#f5f3ef',
  },
  header: {
    backgroundColor: '#5C1A1A',
    paddingHorizontal: 20,
    paddingTop: 48,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoBadge: {
    backgroundColor: '#fff',
    width: 28,
    height: 28,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoBadgeText: {
    color: '#5C1A1A',
    fontSize: 12,
    fontWeight: '800',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '750',
    color: '#fff',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 120,
  },
  profileCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#ece9e4',
    marginBottom: 16,
  },
  avatarContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  avatarLarge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#5C1A1A',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  avatarLargeText: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '800',
  },
  editAvatarBtn: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#f5f3ef',
    borderWidth: 1,
    borderColor: '#ece9e4',
  },
  editAvatarText: {
    fontSize: 11,
    color: '#5C1A1A',
    fontWeight: '700',
  },
  userName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a1a',
    textAlign: 'center',
  },
  userRole: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    marginBottom: 16,
  },
  infoGrid: {
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  infoGridItem: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  infoGridLabel: {
    fontSize: 11,
    color: '#888',
  },
  infoGridValue: {
    fontSize: 12,
    color: '#1a1a1a',
    fontWeight: '700',
    marginTop: 2,
  },
  editProfileBtn: {
    backgroundColor: '#5C1A1A',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  editProfileBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  editForm: {
    gap: 8,
  },
  editLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#666',
    textTransform: 'uppercase',
  },
  editInput: {
    backgroundColor: '#f8f9fa',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#ece9e4',
    fontSize: 14,
    color: '#1a1a1a',
    marginBottom: 6,
  },
  saveBtn: {
    backgroundColor: '#166534',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },
  saveBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  menuSection: {
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ece9e4',
    padding: 8,
  },
  menuItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f3ef',
  },
  menuItemText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '600',
  },
  menuItemArrow: {
    fontSize: 12,
    color: '#5C1A1A',
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  settingsContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 340,
  },
  settingsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  settingsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  settingsClose: {
    fontSize: 13,
    color: '#5C1A1A',
    fontWeight: '700',
  },
  settingsItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f3ef',
  },
  settingsItemLabel: {
    fontSize: 13,
    color: '#333',
  },
  settingsItemValue: {
    fontSize: 13,
    color: '#999',
  },
  popupContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 340,
  },
  popupTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 16,
    textAlign: 'center',
  },
  avatarRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  avatarSelectBubble: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#5C1A1A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarSelectText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  popupCloseBtn: {
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 12,
  },
  popupCloseBtnText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#ece9e4',
    flexDirection: 'row',
    height: 80,
    paddingBottom: 24,
    paddingTop: 10,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#bbb',
  },
  navLabelActive: {
    color: '#5C1A1A',
  },
});