import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#f5f3ef',
  },
  header: {
    backgroundColor: '#5C1A1A',
    paddingHorizontal: 16,
    paddingTop: 48,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  backBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  brandBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  logoBadge: {
    backgroundColor: '#fff',
    width: 28,
    height: 28,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoBadgeText: {
    color: '#5C1A1A',
    fontSize: 12,
    fontWeight: '800',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '850',
    color: '#fff',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 120,
  },
  caseTypeBanner: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ece9e4',
    marginBottom: 16,
    alignItems: 'center',
  },
  caseTypeName: {
    fontSize: 16,
    fontWeight: '750',
    color: '#5C1A1A',
  },
  formGroup: {
    marginBottom: 14,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#666',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  formInput: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#ece9e4',
    fontSize: 14,
    color: '#1a1a1a',
  },
  formTextArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  uneditableField: {
    backgroundColor: '#e6e4df',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#d2cfc9',
  },
  uneditableFieldText: {
    fontSize: 14,
    color: '#555',
    fontWeight: '600',
  },
  dropdownSelector: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#ece9e4',
    justifyContent: 'center',
  },
  dropdownValue: {
    fontSize: 14,
    color: '#1a1a1a',
  },
  dropdownList: {
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ece9e4',
    marginTop: 4,
    maxHeight: 180,
    overflow: 'hidden',
  },
  dropdownItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f3ef',
  },
  dropdownItemText: {
    fontSize: 13,
    color: '#333',
  },
  evidenceSection: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginVertical: 16,
    borderWidth: 1,
    borderColor: '#ece9e4',
  },
  evidenceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  evidenceTitle: {
    fontSize: 14,
    fontWeight: '750',
    color: '#1a1a1a',
  },
  addEvidenceBtn: {
    backgroundColor: '#5C1A1A',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  addEvidenceBtnText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  evidenceHint: {
    fontSize: 11,
    color: '#999',
    marginBottom: 12,
  },
  evidenceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f3ef',
  },
  evidenceInfo: {
    flex: 1,
  },
  evidenceName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333',
  },
  evidenceMeta: {
    fontSize: 11,
    color: '#999',
    marginTop: 2,
  },
  evidenceActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deleteBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#fee2e2',
    borderRadius: 6,
  },
  deleteBtnText: {
    color: '#ef4444',
    fontSize: 11,
    fontWeight: '700',
  },
  submitBtn: {
    backgroundColor: '#5C1A1A',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  submitBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#ece9e4',
    flexDirection: 'row',
    height: 80,
    paddingBottom: 24,
    paddingTop: 10,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#bbb',
  },
});