import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#f5f3ef',
  },
  header: {
    backgroundColor: '#5C1A1A',
    paddingHorizontal: 20,
    paddingTop: 48,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  backText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  logoBadge: {
    backgroundColor: '#fff',
    width: 28,
    height: 28,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoBadgeText: {
    color: '#5C1A1A',
    fontSize: 12,
    fontWeight: '800',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '750',
    color: '#fff',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 120,
  },
  searchBar: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ece9e4',
    paddingHorizontal: 12,
    height: 48,
    justifyContent: 'center',
    marginBottom: 14,
  },
  searchInput: {
    fontSize: 14,
    color: '#333',
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ece9e4',
  },
  filterChipActive: {
    backgroundColor: '#5C1A1A',
    borderColor: '#5C1A1A',
  },
  filterText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
  },
  filterTextActive: {
    color: '#fff',
  },
  lawyerCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#ece9e4',
    gap: 12,
  },
  lawyerAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lawyerAvatarText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
  },
  lawyerInfo: {
    flex: 1,
  },
  lawyerName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  lawyerSpec: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  lawyerMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 12,
  },
  sbcBadge: {
    fontSize: 9,
    color: '#5C1A1A',
    fontWeight: '700',
    backgroundColor: '#f5e8e8',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  ratingText: {
    fontSize: 11,
    color: '#666',
    fontWeight: '700',
  },
  actionButtonsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  actionBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  profileBtn: {
    backgroundColor: '#f5f3ef',
    borderWidth: 1,
    borderColor: '#ece9e4',
  },
  profileBtnText: {
    color: '#5C1A1A',
    fontSize: 11,
    fontWeight: '700',
  },
  requestBtn: {
    backgroundColor: '#5C1A1A',
  },
  requestBtnText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#ece9e4',
    flexDirection: 'row',
    height: 80,
    paddingBottom: 24,
    paddingTop: 10,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#bbb',
  },
  navLabelActive: {
    color: '#5C1A1A',
  },
  lawyerProfileContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 380,
    maxHeight: '80%',
  },
  closeProfileBtn: {
    alignSelf: 'flex-end',
    marginBottom: 10,
  },
  closeProfileText: {
    fontSize: 14,
    color: '#5C1A1A',
    fontWeight: '700',
  },
  profileAvatarLarge: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 10,
  },
  profileAvatarText: {
    fontSize: 24,
    fontWeight: '800',
    color: '#fff',
  },
  profileName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a1a',
    textAlign: 'center',
  },
  profileSpec: {
    fontSize: 13,
    color: '#888',
    textAlign: 'center',
    marginBottom: 14,
  },
  profileDetails: {
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 10,
    marginBottom: 14,
  },
  profileDetailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  profileDetailLabel: {
    fontSize: 11,
    color: '#888',
  },
  profileDetailValue: {
    fontSize: 11,
    color: '#1a1a1a',
    fontWeight: '600',
  },
  profileAbout: {
    fontSize: 12,
    color: '#555',
    lineHeight: 18,
    marginBottom: 14,
    textAlign: 'center',
  },
  scheduleBtn: {
    backgroundColor: '#f5e8e8',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 14,
  },
  scheduleBtnText: {
    color: '#5C1A1A',
    fontSize: 12,
    fontWeight: '700',
  },
  reviewsHeader: {
    fontSize: 14,
    fontWeight: '750',
    color: '#1a1a1a',
    marginBottom: 8,
    marginTop: 8,
  },
  reviewCard: {
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#eee',
  },
  reviewUser: {
    fontSize: 11,
    fontWeight: '700',
    color: '#333',
  },
  reviewComment: {
    fontSize: 11,
    color: '#666',
    marginTop: 2,
  },
  sendRequestBtn: {
    backgroundColor: '#5C1A1A',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },
  sendRequestBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  popupContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 360,
  },
  popupTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 8,
    textAlign: 'center',
  },
  popupCloseBtn: {
    marginTop: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 12,
  },
  popupCloseBtnText: {
    fontSize: 15,
    color: '#666',
    fontWeight: '600',
  },
  scheduleItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  scheduleDay: {
    fontSize: 13,
    fontWeight: '700',
    color: '#333',
  },
  scheduleTime: {
    fontSize: 13,
    color: '#666',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
});